version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/ai-app
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: ec2-user
  AfterInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh aws
      timeout: 60
      runas: ec2-user
